version: '3'

services:
  web-ui:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app.ui.httpd #tag used to group all log of the same type

  fluentd:
    image: sample/fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:5.0
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:5.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"